# Install dependencies for Jekyll

- name: install jekyll dependencies - CentOS
  yum:
             pkg={{ item }}
    update_cache=yes
           state=present
  with_items:
    - gcc
    - gcc-c++
  when: ansible_distribution == "CentOS"

- name: install jekyll dependencies - Ubuntu
  apt: update_cache=yes pkg={{ item }} state=present
  with_items:
    - build-essential
  when: ansible_distribution == "Ubuntu"
